version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cryptocommits/server:latest
    container_name: cryptocommits_server
    ports:
     - "3001:3001"
    volumes:
      - .:/usr/var/app/server
    environment:
      - LIMIT=10
    networks:
      - crypto-network
    command: sh -c "npm run start"

networks:
  crypto-network:
    name: crypto-network
    attachable: true